import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "./_components/sidebar";
import { Toaster } from "sonner";

const inter = Inter({
  display: "auto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stockly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full">
          <Toaster position="bottom-center" />
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
