import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "./_components/sidebar";

const inter = Inter({
  display: "auto",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Stockly",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full gap-8">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
